language: node_js
node_js:
 - "13"

cache:
  directories:
    - a/node_modules
    - b/node_modules

install:
  - npm install
  - npm --prefix ./a install ./a
  - npm --prefix ./b install ./b

script:
  - if git diff --name-only HEAD^ | grep -c "a/"; then
      cd a;
      npm run lint &&
      npm run test -- --coverage --watchAll=false &&
      npm run build;
    fi
  - if git diff --name-only HEAD^ | grep -c "b/"; then
      cd ../b;
      npm run lint &&
      npm run test -- --coverage --watchAll=false &&
      npm run build;
    fi
