language: node_js
node_js:
 - "13"

cache:
  directories:
    - a/node_modules
    - b/node_modules

install:
  - npm install
  - npm --prefix ./a install ./a
  - npm --prefix ./b install ./b

script:
  - if output=$(git status --short | grep -c a/); then
      cd a;
      npm run lint;
      npm run test;
      npm run build;
    fi
  - if output=$(git status --short | grep -c b/); then
      cd b;
      npm run lint;
      npm run test;
      npm run build;
    fi
