sudo: required
services: docker
branches:
  only: master
env:
  global:
  - GCP_PROJECT_ID=react-cicd-travis-cloud-run
  - IMAGE_PROJECT_A=gcr.io/react-cicd-travis-cloud-run/cicd-react-cloud-run
  - IMAGE_PROJECT_B=gcr.io/react-cicd-travis-cloud-run/second-project
  - TEST_IMAGE=gcr.io/cicd-react-cloud-run
  - CLOUD_RUN_SERVICE_PROJECT_1=cicd-react-cloud-run
  - CLOUD_RUN_SERVICE_PROJECT_2=second-project
  - CLOUD_RUN_REGION=asia-northeast1
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_0e5954dbbcc6_key -iv $encrypted_0e5954dbbcc6_iv -in gcp-key.json.enc -out gcp-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=gcp-key.json
- gcloud auth configure-docker    # enable "docker push" to gcr
- gcloud config set project "${GCP_PROJECT_ID}"
install:
  - npm install
  - npm --prefix ./a install ./a
  - npm --prefix ./b install ./b
script:
- if git diff --name-only HEAD^ | grep -c "a/"; then
    set -ex;
    cd a;
    npm run lint &&
    npm run test -- --coverage --watchAll=false;
    docker build -t "${IMAGE_PROJECT_A}:${TRAVIS_COMMIT}" ./a && \
    docker push "${IMAGE_PROJECT_A}:${TRAVIS_COMMIT}" && \
    gcloud run deploy "${CLOUD_RUN_SERVICE_PROJECT_1}" \
      --image="${IMAGE_PROJECT_A}:${TRAVIS_COMMIT}" \
      --platform=managed \
      --region="${CLOUD_RUN_REGION}" \
      --allow-unauthenticated;
    set +x
  fi
- if git diff --name-only HEAD^ | grep -c "b/"; then
    set -ex;
    cd ../b;
    npm run lint &&
    npm run test -- --coverage --watchAll=false;
    docker build -t "${IMAGE_PROJECT_B}:${TRAVIS_COMMIT}" ./b && \
    docker push "${IMAGE_PROJECT_B}:${TRAVIS_COMMIT}" && \
    gcloud run deploy "${CLOUD_RUN_SERVICE_PROJECT_2}" \
      --image="${IMAGE_PROJECT_B}:${TRAVIS_COMMIT}" \
      --platform=managed \
      --region="${CLOUD_RUN_REGION}" \
      --allow-unauthenticated;
    set +x
  fi
